### ISSUE TITLE
Participation in MSR Hackathon: MPR

### ISSUE THREAD

**Issue by nhasabni** [MSRHack2022/Hackathon#1]
Tentative participants: Niranjan Hasabnis
Project idea: Quality survey of open-source repositories -- how many repositories contain code that can be built, etc.

**Comment by jgbarah** [comment]
Thanks for your intent to participate! Please, start browsing documentation about GrimoireLab, if you want. You can start by reading https://doi.org/10.7717/peerj-cs.601 to have a more concrete idea about what GrimoireLab can do, if you are not familiar with it.

**Comment by jgbarah** [comment]
Please, fill in this questionnaire at your earliest convenience: https://forms.gle/Rr2QbfWZmigxvwFa7

Using data from it, we will contact you to inform about the training sessions, and next steps.

**Comment by maelick** [comment]
Hei Niranjan @nhasabni. It looks like you haven't yet filled the [form](https://forms.gle/Rr2QbfWZmigxvwFa7). Remember to do it as soon as possible so we can send you the invite link for tomorrow's training session :-)

**Comment by jgbarah** [comment]
@nhasabni, if you're still intending to participate, please fill in the form asap. We already had some training sessions, and we should send you a link to the recordings, and an invite to the next one.

**Comment by nhasabni** [comment]
@jgbarah Sorry for delay in responding. I am interested to participate. I've filled the form. Can you tell me my next steps?

**Comment by jgbarah** [comment]
We have just sent a message to all participants who filled in the form. If for some reason you didn't receive it, please comment here (and ensure you already filled in the form). If you already received the message, please comment that you did, and close the issue (so we know everything is in order for now).

Thanks for your participation!

**Comment by nirhasabnis** [comment]
I received the messages. We can close the issue. Thanks.

**Comment by nirhasabnis** [comment]
My matrix username is nirhasabnis.

**Comment by jgbarah** [comment]
Good. Closing the issue.
