### ISSUE TITLE
Participation in MSR Hackathon: PRM

### ISSUE THREAD

**Issue by pooya-rostami** [MSRHack2022/Hackathon#2]
Participant: Pooya Rostami Mazrae
Project Idea: bot detection in open-source repositories

**Comment by jgbarah** [comment]
Thanks for your intent to participate! Please, start browsing documentation about GrimoireLab, if you want. You can start by reading https://doi.org/10.7717/peerj-cs.601 to have a more concrete idea about what GrimoireLab can do, if you are not familiar with it.

**Comment by tommens** [comment]
Hello Jesus and Pooya, @pooya-rostami is a new PhD student of mine, starting in October to work under my supervision, as is the case as well for @natti07 who also submitted an issue #3 for the hackathon. Great idea, to have this GrimoireLab Hackathon!

**Comment by jgbarah** [comment]
Please, fill in this questionnaire at your earliest convenience: https://forms.gle/Rr2QbfWZmigxvwFa7

Using data from it, we will contact you to inform about the training sessions, and next steps.

**Comment by jgbarah** [comment]
We have just sent a message to all participants who filled in the form. If for some reason you didn't receive it, please comment here (and ensure you already filled in the form). If you already received the message, please comment that you did, and close the issue (so we know everything is in order for now).

Thanks for your participation!

**Comment by pooya-rostami** [comment]
Hello, I have received an email and I have filled the form before.
Thanks.
